### ISSUE TITLE
Is --quick really faster on importing?

### ISSUE THREAD

**Issue by shyim** [doutorfinancas/go-mad#14]
First thanks for building this ❤️ 

I understand from the description that is creating for any record an own `INSERT INTO`.  Does it maybe make more sense to have an insert into row limiter rather than. like `--insert-into-limit=50` adds only 50 records to insert into 

And I would like to embed this into a cli command

**Comment by bolovsky** [comment]
Hey!

You are very much welcome. Just figured I needed something else and it would require much change in the two projects I was looking at.

the `--quick` flag is definitely not faster on import, just better/faster on large table export. I try that all the flags are `mysqldump` compatible and current behaviour is either you have 1 by 1 or you have 100 by 100.

This feature seems nice, can definitely add. During next week I will also work on this and will create a release as soon as it's stable enough for it :smile: 

if you wish to contribute or have any more requests, feel free to drop in

**Comment by bolovsky** [comment]
That flag is now available for cli usage @shyim 

:smile:
