### ISSUE TITLE
Hex blob columns

### ISSUE THREAD

**Issue by shyim** [doutorfinancas/go-mad#19]
Hey,

we use for all tables UUIDs saved in binary(16). Those fields should be hexed in the output SQL

**Comment by bolovsky** [comment]
Hey!

Can have a look at it, but as the tool works right now, I have no idea on the type of what is being returned by mysql, so everything is handled as a string.

Sounds legit though, so will try to have a look on changing that

**Comment by shyim** [comment]
I would suggest replace this query https://github.com/doutorfinancas/go-mad/blob/master/database/mysql.go#L365

with `SHOW COLUMS FROM x`

select limit 1 looks like a dirty way to get the columns

**Comment by bolovsky** [comment]
Yeah, that would be a way, but since I already hook into create table, might be a bit cleaner and 1 less query. have a look at the PR :)

**Comment by shyim** [comment]
Wow. Looks perfect. I love u ❤️.
I will test in later😅

**Comment by bolovsky** [comment]
Great! let me know if it went well :) I will only be able to test it in a couple of days

**Comment by bolovsky** [comment]
Found the issue in the PR and fixed it :) it's a zap logger known issue on OSX (using linux here), fixed :)

**Comment by shyim** [comment]
Looks pretty good.

![image](https://user-images.githubusercontent.com/6224096/151961683-5676718f-3329-47e6-b545-281c5255e0e4.png)

![image](https://user-images.githubusercontent.com/6224096/151961773-54d88e37-3b25-4120-9406-c707426a42e7.png)


Will create an issue for the other bug 😂

**Comment by bolovsky** [comment]
Nice! Will merge this then!
