### ISSUE TITLE
Ignore generated columns

### ISSUE THREAD

**Issue by shyim** [doutorfinancas/go-mad#26]
![image](https://user-images.githubusercontent.com/6224096/151961871-a2e8b306-66b2-42a2-9eec-2b791a5134e9.png)

```
CREATE TABLE `product_keyword_dictionary` (
  `id` binary(16) NOT NULL,
  `language_id` binary(16) NOT NULL,
  `keyword` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `reversed` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (reverse(`keyword`)) STORED,
  PRIMARY KEY (`id`,`language_id`),
  UNIQUE KEY `uniq.language_id_keyword` (`language_id`,`keyword`),
  KEY `idx.product_keyword_dictionary.language_id` (`language_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

```
ERROR 3105 (HY000) at line 11000: The value specified for generated column 'reversed' in table 'product_keyword_dictionary' is not allowed.
```

**Comment by bolovsky** [comment]
Okay, got a pull request that fixes that. Since I don't think generated columns should always be removed, there is a flag you can use for that end. The error may be related with a missing function also. I will eventually add support to export functions, triggers and stored procedures :)

**Comment by shyim** [comment]
I would expect that in the INSERT INTO that column is missing 🙈  as MySQL generates it by own 😅

**Comment by bolovsky** [comment]
uhhh, should be missing, probably forgot something xD

**Comment by bolovsky** [comment]
yeap, forgot to add to parsing of columns :man_shrugging: 
done, should be okay, added tests to make sure it should run as expected

**Comment by bolovsky** [comment]
where you able to test on your side @shyim ?

**Comment by shyim** [comment]
Yes, but I expected that the data is missing on the generated column 🙈 

without flag:

INSERT INTO product_keyword_dictionary (normal, generated)

with flag:

INSERT INTO product_keyword_dictionary (normal)

**Comment by bolovsky** [comment]
ah! Understood. With the flag it will fix the issue, but without the flag it still requires the generated data to be skipped.

Got it!

**Comment by bolovsky** [comment]
@shyim rewrote slightly to make sure generated columns are always skipped in insert, but on created statement is skipped only with flag

**Comment by shyim** [comment]
Now it fails with at line 12003: Column count doesn't match value count at row 1

When we remove the columns, we need to name any column then :D

**Comment by bolovsky** [comment]
Alright, will fix that. Makes sense, all columns should be named when generated columns exist.

**Comment by shyim** [comment]
[sw6.zip](https://github.com/doutorfinancas/go-mad/files/7986607/sw6.zip)
by the way, thats the Database. Maybe it helps you. 😅

**Comment by bolovsky** [comment]
it will help, but can't test today. I did however fixed it, if you happen to have the time to check @shyim :smile:

**Comment by bolovsky** [comment]
Alright, tested with the database you send and now, the `product_keyword_dictionary` only has 3 values and the columns are named. Was also able to reimport the generated dump, so everything should go as expected.

Will merge and create a new release :)
