### ISSUE TITLE
Progress bar to show progress

### ISSUE THREAD

**Issue by shyim** [doutorfinancas/go-mad#30]
Currently, the only way to see what it is doing is to run `SHOW processlist` in another terminal.

Make we could add a progress bar which table is currently worked on 😅

**Comment by shyim** [comment]
But It did run well. Have now a 19GB dump 😂 . 
![image](https://user-images.githubusercontent.com/6224096/152791234-22a8692b-234d-47ce-abdc-6d9bbb317e6b.png)

**Comment by bolovsky** [comment]
it can be done, but this needs to be implemented carefully, as we cannot be changing the output of the console if output is STDOUT :)

Sounds good though ;)

PS: if output is stdout, one could use `pv` ;)

**Comment by shyim** [comment]
I guess is not worth pv works well :)
