### ISSUE TITLE
Rewrite breaks insert into statement

### ISSUE THREAD

**Issue by shyim** [doutorfinancas/go-mad#31]
```
INSERT INTO `user` (`id`, 'faker.Person.Name()' AS `username`)
```

It looks like rewritemap is applied too early

**Comment by shyim** [comment]
or `getColumnsForSelect` returns a struct with two functions then getRewritedColumns, getColumns

**Comment by bolovsky** [comment]
Both solutions are legit, the second one may be a bit cleaner but will increase (slightly) the memory footprint.

If you want to open a PR :heart:, go for the one you feel would be the best :slightly_smiling_face:

**Comment by shyim** [comment]
I am struggling with the current tests. They fail weird 😅
