### ISSUE TITLE
Database Triggers are missing

### ISSUE THREAD

**Issue by shyim** [doutorfinancas/go-mad#38]
Hey,

when the Database contains Database Triggers the output SQL does not contain triggers

**Comment by bolovsky** [comment]
Hey!

Currently we are not exporting neither triggers, nor functions & SP.

Going to add this to the pipeline, might work on it in the next days :)

**Comment by bolovsky** [comment]
Created release with it, since it has some major changes, it's now on 0.3.0 ;)

Thanks for the PR :)
